/** 
 * Generated by go2dts
 *
 * Source: editor.go
 **/

export type EditorStageStatus = "todo" | "running" | "done" | "failed"

export type EditorState = "unknown" | "failed" | "starting" | "does not exist" | "running" | "stopping" | "stopped" | "resuming" | "destroying"

export interface EditorStatus {
  name: string
  realmID: string
  bundleID: string
  createdAt?: Time
  lastActiveAt?: Time
  status: EditorState
  statusMessage: string
  stages: EditorStage[]
  editorURL: string
}

export interface EditorListResponse {
  page: PageMeta
  data?: EditorStatus[]
}

