/** 
 * Generated by go2dts
 *
 * Source: functions.go
 **/

export interface FunctionResponse {
  id?: UUID
  createdAt: Time
  updatedAt: Time
  bundleId: UUID
  name: string
  image: string
  command: string
  environment: {[key: string]: string}
  secrets: string[]
  schema: any
  deployed: boolean
  deploymentStatus: string
  url: string
}

export interface FunctionInstanceResponse {
  id?: UUID
  createdAt: Time
  updatedAt: Time
  bundleId: UUID
  name: string
  image: string
  command: string
  environment: {[key: string]: string}
  secrets: string[]
  schema: any
  deployed: boolean
  deploymentStatus: string
  url: string
}

export interface FunctionListResponse {
  page: PageMeta
  data?: FunctionResponse[]
}

