/** 
 * Generated by go2dts
 *
 * Source: jobs.go
 **/

export type Time = string

export type UUID = string

export type TriggerType = "user" | "apikey" | "schedule" | "webhook" | "unknown"

export interface JobResponse {
  id: string
  lastRunAt?: Time
  bundleID: UUID
  url: string
  name: string
  description: string
  notebookPath: string
  schedule: string
  environment: {[key: string]: string}
  secrets: string[]
  success: boolean
  internal: boolean
}

export interface JobListResponse {
  data?: JobResponse[]
}

export interface JobRunRequest {
  environment: {[key: string]: string}
}

export interface JobRunResponse {
  executionID: string
}

export interface JobSpecification {
  schedule: string
  image: string
  command: string[]
  environment: {[key: string]: string}
  secrets: string[]
}

export interface TriggeredBy {
  type: TriggerType
  id: string
  name: string
}

export interface ExecutionResponse {
  id: string
  jobID: string
  bundleID: string
  jobName: string
  startedAt: Time
  completedAt?: Time
  success: boolean
  specification: JobSpecification
  triggeredBy: TriggeredBy
}

export interface ExecutionStatus {
  startedAt: Time
  completedAt?: Time
  success: boolean
}

export interface ExecutionListResponse {
  data?: ExecutionResponse[]
}

export interface LogMessage {
  timestamp: Time
  msg: string
}

export interface LogsResponse {
  status: ExecutionStatus
  data: LogMessage[]
}

