/** 
 * Generated by go2dts
 *
 * Source: secrets.go
 **/

export interface CreateSecretRequest {
  bundleId: UUID
  name: string
  value: string
}

export interface BundleSecretResponse {
  id?: UUID
  createdAt: Time
  bundleId: UUID
  name: string
}

export interface SecretListResponse {
  page: PageMeta
  data: BundleSecretResponse[]
}

